credentials:
  usernames:
    amar:
      email: areply505@gmail.com 
      name: Amar Ray
      password: $2b$12$XKsRPC1tSE/lML87q6x1m.7KDmXwQ/ofR39u7NT3wHqESNckoAxRO 
    shubham:
      email: shubham.srivastava@vedsu.com
      name: Shubham Srivastava
      # To be replaced with hashed password
      password: $2b$12$WgEIz3hLNDiGs7ijFpvJmOktrws8cetFqqo7Qd2Ynr4psJlMOhFwy 
cookie:
  expiry_days: 0
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail
